

#Scalars

## Scalars (Rank 0 Tensors) in Basic Python




In [1]:
x = 25

In [2]:
x

25

In [3]:
type(x)

int

In [4]:
x_float = 25.0

In [5]:
x_float

25.0

In [6]:
type(x_float)

float

## Scalars in PyTorch

In [8]:
import torch

In [18]:
x_pt = torch.tensor(25)

In [19]:
x_pt

tensor(25)

In [20]:
x_pt.dtype

torch.int64

In [11]:
x_pt.shape

torch.Size([])

In [12]:
x_pt = torch.tensor(25, dtype = torch.float16 )

In [13]:
x_pt

tensor(25., dtype=torch.float16)

In [14]:
x_pt = torch.tensor(25.0)

In [15]:
x_pt

tensor(25.)

In [16]:
x_pt.dtype

torch.float32

In [21]:
x_pt = torch.tensor(25, dtype = torch.int8)

In [22]:
x_pt

tensor(25, dtype=torch.int8)

In [23]:
x_pt = torch.tensor(25, dtype = torch.int)

In [24]:
x_pt

tensor(25, dtype=torch.int32)

## Scalars in TensorFlow

In [27]:
import tensorflow as tf

In [28]:
x_tf = tf.Variable(25, dtype = tf.int16)

In [29]:
x_tf

<tf.Variable 'Variable:0' shape=() dtype=int16, numpy=25>

In [30]:
x_tf.shape

TensorShape([])

In [31]:
y_tf = tf.Variable(3, dtype = tf.int16)

In [32]:
y_tf

<tf.Variable 'Variable:0' shape=() dtype=int16, numpy=3>

In [34]:
tf_sum1 = x_tf + y_tf

In [35]:
tf_sum1

<tf.Tensor: shape=(), dtype=int16, numpy=28>

In [36]:
tf_sum2 = tf.add(x_tf, y_tf)

In [37]:
tf_sum2

<tf.Tensor: shape=(), dtype=int16, numpy=28>

In [38]:
tf_sum2.numpy()

28

# Vectors

## Vectors as  Numpy ndarray objects

In [39]:
import numpy as np

In [40]:
x = np.array([25, 2, 5])

In [41]:
x

array([25,  2,  5])

In [42]:
x.shape

(3,)

In [43]:
np.ndim(x)

1

In [44]:
len(x)

3

In [45]:
type(x)

numpy.ndarray

In [46]:
x[0]

25

In [47]:
type(x[0])

numpy.int64

## Vector Transposition

In [48]:
x_T = x.T

In [49]:
x_T

array([25,  2,  5])

In [50]:
x

array([25,  2,  5])

In [51]:
y = np.array([[25,  2,  5]])

In [52]:
y.shape

(1, 3)

In [53]:
y_T = y.T

In [54]:
y_T

array([[25],
       [ 2],
       [ 5]])

In [55]:
y_T.shape

(3, 1)

In [56]:
y_T.T

array([[25,  2,  5]])

## Norms

### L2 Norm (Euclidean Distance)

In [57]:
(25**2 + 2**2 + 5**2) ** (1/2)

25.573423705088842

In [58]:
y

array([[25,  2,  5]])

In [59]:
np.linalg.norm(y)

25.573423705088842

In [60]:
x

array([25,  2,  5])

In [61]:
np.linalg.norm(x)

25.573423705088842

### L1 Norm (Manhattan Distance)



In [62]:
np.abs(25) + np.abs(2) + np.abs(5)

32

### Squared L2 *Norm*

In [64]:
(25**2 + 2**2 + 5**2)

654

### Max Norm

In [66]:
np.max([np.abs(25), np.abs(2), np.abs(5)])

25

## Dot Product of a vector

In [67]:
x

array([25,  2,  5])

In [68]:
y = np.array([2, 3, 4])

In [69]:
y

array([2, 3, 4])

In [71]:
np.dot(x, y)

76