

#Scalars

## Scalars (Rank 0 Tensors) in Basic Python




In [1]:
x = 25

In [2]:
x

25

In [3]:
type(x)

int

In [4]:
x_float = 25.0

In [5]:
x_float

25.0

In [6]:
type(x_float)

float

## Scalars in PyTorch

In [7]:
import torch

In [8]:
x_pt = torch.tensor(25)

In [9]:
x_pt

tensor(25)

In [10]:
x_pt.dtype

torch.int64

In [11]:
x_pt.shape

torch.Size([])

In [12]:
x_pt = torch.tensor(25, dtype = torch.float16 )

In [13]:
x_pt

tensor(25., dtype=torch.float16)

In [14]:
x_pt = torch.tensor(25.0)

In [15]:
x_pt

tensor(25.)

In [16]:
x_pt.dtype

torch.float32

In [17]:
x_pt = torch.tensor(25, dtype = torch.int8)

In [18]:
x_pt

tensor(25, dtype=torch.int8)

In [19]:
x_pt = torch.tensor(25, dtype = torch.int)

In [20]:
x_pt

tensor(25, dtype=torch.int32)

## Scalars in TensorFlow

In [21]:
import tensorflow as tf

In [22]:
# Variable Documentation: https://www.tensorflow.org/guide/variable
x_tf = tf.Variable(25, dtype = tf.int16)

In [23]:
x_tf

<tf.Variable 'Variable:0' shape=() dtype=int16, numpy=25>

In [24]:
x_tf.shape

TensorShape([])

In [25]:
y_tf = tf.Variable(3, dtype = tf.int16)

In [26]:
y_tf

<tf.Variable 'Variable:0' shape=() dtype=int16, numpy=3>

In [27]:
tf_sum1 = x_tf + y_tf

In [28]:
tf_sum1

<tf.Tensor: shape=(), dtype=int16, numpy=28>

In [29]:
tf_sum2 = tf.add(x_tf, y_tf)

In [30]:
tf_sum2

<tf.Tensor: shape=(), dtype=int16, numpy=28>

In [31]:
tf_sum2.numpy()

28

# Vectors

## Vectors as  Numpy ndarray objects

In [32]:
import numpy as np

In [33]:
x = np.array([25, 2, 5])

In [34]:
x

array([25,  2,  5])

In [35]:
x.shape

(3,)

In [36]:
np.ndim(x)

1

In [37]:
len(x)

3

In [38]:
type(x)

numpy.ndarray

In [39]:
x[0]

25

In [40]:
type(x[0])

numpy.int64

## Vector Transposition

In [41]:
x_T = x.T

In [42]:
x_T

array([25,  2,  5])

In [43]:
x

array([25,  2,  5])

In [44]:
y = np.array([[25,  2,  5]])

In [45]:
y.shape

(1, 3)

In [46]:
y_T = y.T

In [47]:
y_T

array([[25],
       [ 2],
       [ 5]])

In [48]:
y_T.shape

(3, 1)

In [49]:
y_T.T

array([[25,  2,  5]])

## Norms

### L2 Norm (Euclidean Distance)

In [50]:
(25**2 + 2**2 + 5**2) ** (1/2)

25.573423705088842

In [51]:
y

array([[25,  2,  5]])

In [52]:
np.linalg.norm(y)

25.573423705088842

In [53]:
x

array([25,  2,  5])

In [54]:
np.linalg.norm(x)

25.573423705088842

### L1 Norm (Manhattan Distance)



In [55]:
np.abs(25) + np.abs(2) + np.abs(5)

32

### Squared L2 *Norm*

In [56]:
(25**2 + 2**2 + 5**2)

654

### Max Norm

In [57]:
np.max([np.abs(25), np.abs(2), np.abs(5)])

25

## Dot Product of a vector

In [58]:
x

array([25,  2,  5])

In [59]:
y = np.array([2, 3, 4])

In [60]:
y

array([2, 3, 4])

In [61]:
np.dot(x, y)

76

## Basis Vectors

* 1\. Basis Vector Concept: https://www.geeksforgeeks.org/basis-vectors-in-linear-algebra-ml/ 
* 2\.Rank of a matrix
    * 2.1\. Concept: https://www.youtube.com/watch?v=WvJ6U_tnPIQ
    * 2.2\. program: https://www.geeksforgeeks.org/program-for-rank-of-matrix/ 
    * 2.3\. Wiki page: https://en.wikipedia.org/wiki/Row_echelon_form

## Orthogonal Vectors & Orthonormal Vectors

* Refer: https://www.ucl.ac.uk/~ucahmdl/LessonPlans/Lesson10.pdf

- When dot product of two vectors is 0, those vectors are considered as orthogonal vectors.
- If the orthogonal vectors are also unit vectors, then those vectors are called a orthonormal vectors.

In [62]:
i = np.array([1,0])

In [63]:
j = np.array([0,1])

In [64]:
np.dot(i, j)

0

# Matrices



* Two Dimensional tensors



## Define matrix using NumPy

In [65]:
X = np.array([
              [25, 2],
              [5, 26],
              [3, 7]
])

In [67]:
type(X)

numpy.ndarray

In [73]:
# Shape property provides the array dimension 
# (Refer https://numpy.org/doc/stable/reference/generated/numpy.ndarray.shape.html)
X.shape

(3, 2)

In [74]:
# Number of elements in an array (product of row x col)
X.size

6

In [75]:
np.prod(X.shape)

6

### Slicing a matrix

In [76]:
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [84]:
# Extract 2nd column
X[:, 1]

array([ 2, 26,  7])

In [85]:
# Extract 1st column
X[:, 0]

array([25,  5,  3])

In [86]:
# Extract 2nd row
X[1, :]

array([ 5, 26])

In [88]:
# Extract 2nd row (column is fully represented with start and end values)
X[1, 0:2]

array([ 5, 26])

In [93]:
# Extract 2nd and 3rd rows
X[1:, :]

array([[ 5, 26],
       [ 3,  7]])

## Defining matrix using pytorch

In [94]:
X_pt = torch.tensor([
              [25, 2],
              [5, 26],
              [3, 7]
])

In [95]:
X_pt

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [96]:
X_pt.shape

torch.Size([3, 2])

### Slicing

In [97]:
X_pt[1, :]

tensor([ 5, 26])

## Defining Matrix using TensorFlow

In [98]:
X_tf = tf.Variable([
              [25, 2],
              [5, 26],
              [3, 7]
])

In [99]:
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25,  2],
       [ 5, 26],
       [ 3,  7]], dtype=int32)>

In [101]:
# Get the dimension of the tensor (2 => matrix)
tf.rank(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [104]:
# Matrix dimension (row x col)
tf.shape(X_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2], dtype=int32)>

# Higher Rank Tensors

For hand-written digit recognition (MNIST dataset), we will be using four dimensional tensor.
1. Number of images in the training batch.  (eg., 32)
2. Image Height in pixels (eg., 28)
3. Image Width in pixels (eg., 28)
4. Color of the pixel (in RGB) (eg., 3)

## Pytorch

In [105]:
image_pt = torch.zeros([32, 28, 28, 3])

In [106]:
image_pt

tensor([[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         ...,

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0.

## Tensorflow

In [107]:
image_tf = tf.zeros([32, 28, 28, 3])

In [108]:
image_tf

<tf.Tensor: shape=(32, 28, 28, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        ...,

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


   